server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: bank-credit-facility
  main:
    banner-mode: off
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:bankcreditfacility
    username: root
    password: root
    driver-class-name: org.h2.Driver
    platform: h2
